Repository twilio/twilio-verify-ios, pull requests merged in 2020-11, with the labels that each got.

#107 [ACCSEC-19361] - Added public method to clear local storage
  README.md
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/TwilioVerify/Sources/Data/Storage.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorRepository.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerifyManager.swift
  TwilioVerifyDemo/TwilioVerifyDemo/TwilioVerify/TwilioVerifyAdapter.swift
  TwilioVerifyTests/TwilioVerify/Sources/Data/Mocks/StorageProviderMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Data/StorageTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/FactorFacadeTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/FactorRepositoryTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/Mocks/FactorRepositoryMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/Mocks/PushFactoryMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/PushFactoryTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Manager/Mocks/FactorFacadeMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Manager/TwilioVerifyManagerTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/TwilioVerifyTests.swift
Labels: Documentation, Enhancement

#108 Version 0.2.0
  README.md
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/TwilioVerify/Sources/Data/Storage.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorRepository.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerifyManager.swift
  TwilioVerifyDemo/TwilioVerifyDemo/TwilioVerify/TwilioVerifyAdapter.swift
  TwilioVerifyTests/TwilioVerify/Sources/Data/Mocks/StorageProviderMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Data/StorageTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/FactorFacadeTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/FactorRepositoryTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/Mocks/FactorRepositoryMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/Mocks/PushFactoryMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/PushFactoryTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Manager/Mocks/FactorFacadeMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Manager/TwilioVerifyManagerTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/TwilioVerifyTests.swift
Labels: Enhancement

#112 [Housekeeping] - Fixes Issue when presenting Challenge screen from a push notification
  TwilioVerifyDemo/TwilioVerifyDemo/Common/AppDelegate.swift
Labels: Housekeeping

#95 [ACCSEC-18940] - Logging Foundation
  DangerFile
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
  TwilioVerify/TwilioVerify/Sources/Logger/DefaultLogger.swift
  TwilioVerify/TwilioVerify/Sources/Logger/Logger.swift
  TwilioVerify/TwilioVerify/Sources/Logger/OSLogWrapper.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/BaseFactorTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/CreateFactorTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/DeleteFactorTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/GetAllChallengesTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/GetChallengeTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/TwilioVerifyTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/UpdateChallengeTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/UpdateFactorTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/VerifyFactorTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Logger/DefaultLoggerTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Logger/Mocks/LoggerServiceMock.swift
  TwilioVerifyTests/TwilioVerify/Sources/Logger/Mocks/LoggerTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Logger/Mocks/OSLogWrapperMock.swift
Labels: Enhancement
