Repository twilio/twilio-verify-ios, pull requests merged in 2021-11, with the labels that each got.

#168 [Feature] Support notification platform "none"
  TwilioVerifyDemo/TwilioVerifyDemo/Common/View/Base.lproj/Main.storyboard
  TwilioVerifyDemo/TwilioVerifyDemo/CreateFactor/Presenter/CreateFactorPresenter.swift
  TwilioVerifyDemo/TwilioVerifyDemo/CreateFactor/View/CreateFactorViewController.swift
  TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
  TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerifySDK/TwilioVerify/Sources/Models/FactorPayload.swift
  TwilioVerifySDK/TwilioVerify/Sources/Models/UpdateFactorPayload.swift
  TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Factor/Mocks/PushFactoryMock.swift
  TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Factor/PushFactoryTests.swift
Labels: Enhancement, DO NOT MERGE YET

#172 Store notification platform
  TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/FactorMapper.swift
  TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/DTOs/PushFactorDTO.swift
  TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/PushFactor.swift
  TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Factor/FactorMapperTests.swift
Labels: Enhancement

#173 Set default value for notification platform
  TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/DTOs/PushFactorDTO.swift
  TwilioVerifySDK/TwilioVerify/Sources/Domain/Factor/Models/PushFactor.swift
  TwilioVerifySDKTests/TwilioVerify/Sources/Domain/Factor/FactorMapperTests.swift
Labels: Bug
