Repository twilio/twilio-verify-ios, pull requests merged in 2021-02, with the labels that each got.

#123 Version 0.3.2
  Scripts/bump-version.swift
  Scripts/env.sh
  Scripts/generate-docs.sh
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/Config/Version.xcconfig
  TwilioVerify/Info.plist
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift
  TwilioVerify/TwilioVerify/Sources/TwilioVerifyConfig.swift
  TwilioVerifyDemo/TwilioVerifyDemo.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: Bug

#125 ACCSEC-20143 Validate device token for push
  TwilioVerifyDemo/TwilioVerifyDemo/CreateFactor/Presenter/CreateFactorPresenter.swift
Labels: Housekeeping

#122 [ACCSEC-18905] Distribute sample app
  .circleci/config.yml
  Gemfile.lock
  Scripts/change-base-url.swift
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
  TwilioVerify/TwilioVerify/Sources/TwilioVerifyConfig.swift
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/Pluginfile
  fastlane/README.md
Labels: Enhancement
