Repository twilio/twilio-verify-ios, pull requests merged in 2021-01, with the labels that each got.

#114 feat: Support react native bridge
  .gitignore
  Gemfile.lock
  Scripts/bump-version.swift
  Scripts/generate-docs.sh
  TwilioVerify/Config/Version.xcconfig
  TwilioVerify/Info.plist
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift
Labels: Enhancement

#116 ACCSEC-19763 Update readme to include note
  Gemfile
  Gemfile.lock
  README.md
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Documentation

#115 ACCSEC-19003 Add logs
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/TwilioSecurity/Sources/Key/Signer/ECSigner.swift
  TwilioVerify/TwilioSecurity/Sources/Key/Template/ECP256SignerTemplate.swift
  TwilioVerify/TwilioSecurity/Sources/Keychain/KeyManager.swift
  TwilioVerify/TwilioSecurity/Sources/Keychain/Keychain.swift
  TwilioVerify/TwilioSecurity/Sources/Storage/SecureStorage.swift
  TwilioVerify/TwilioVerify/Sources/API/ChallengeAPIClient.swift
  TwilioVerify/TwilioVerify/Sources/API/FactorAPIClient.swift
  TwilioVerify/TwilioVerify/Sources/Data/KeyStorage.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Challenge/ChallengeFacade.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Challenge/ChallengeListMapper.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Challenge/ChallengeMapper.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Challenge/ChallengeRepository.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Challenge/PushChallengeProcessor.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorFacade.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorMapper.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/FactorRepository.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Manager/TwilioVerify.swift
  TwilioVerify/TwilioVerify/Sources/Extensions/StringInterpolation+Extensions.swift
  TwilioVerify/TwilioVerify/Sources/Extensions/URLSession+Extensions.swift
  TwilioVerify/TwilioVerify/Sources/Logger/Logger.swift
  TwilioVerify/TwilioVerify/Sources/Networking/Authentication.swift
  TwilioVerify/TwilioVerify/Sources/Networking/NetworkProvider.swift
  TwilioVerify/TwilioVerify/Sources/Networking/URLRequestBuilder.swift
  TwilioVerify/TwilioVerify/Sources/TwilioVerifyError.swift
  TwilioVerifyDemo/TwilioVerifyDemo.xcodeproj/project.pbxproj
  TwilioVerifyDemo/TwilioVerifyDemo/ChallengeDetail/Presenter/ChallengeDetailPresenter.swift
  TwilioVerifyDemo/TwilioVerifyDemo/Common/AppDelegate.swift
  TwilioVerifyDemo/TwilioVerifyDemo/Common/DIContainer.swift
  TwilioVerifyDemo/TwilioVerifyDemo/CreateFactor/Presenter/CreateFactorPresenter.swift
  TwilioVerifyDemo/TwilioVerifyDemo/FactorDetail/Presenter/FactorDetailPresenter.swift
  TwilioVerifyDemo/TwilioVerifyDemo/FactorList/Presenter/FactorListPresenter.swift
  TwilioVerifyDemo/TwilioVerifyDemo/TwilioVerify/TwilioVerifyAdapter.swift
  TwilioVerifyTests/TwilioVerify/Sources/API/ChallengeAPIClientTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Challenge/ChallengeFacadeTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Challenge/ChallengeRepositoryTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Challenge/PushChallengeProcessorTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Domain/Factor/FactorFacadeTests.swift
  TwilioVerifyTests/TwilioVerify/Sources/Integration/APIResponses/create_factor_valid_response.json
  TwilioVerifyTests/TwilioVerify/Sources/Integration/APIResponses/get_challenges_valid_response.json
  TwilioVerifyTests/TwilioVerify/Sources/Integration/APIResponses/verify_factor_valid_response.json
Labels: Enhancement

#118 [ACCSEC-19719] Add logging documentation
  README.md
  TwilioVerify/TwilioVerify/Sources/Logger/Logger.swift
Labels: Documentation

#117 Version 0.3.0
  .github/CODEOWNERS
  .gitignore
  Gemfile
  Gemfile.lock
  Provisioning Profiles.tar.enc
  README.md
  Scripts/bump-version.swift
  Scripts/generate-docs.sh
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/Config/Version.xcconfig
  TwilioVerify/Info.plist
  TwilioVerify/TwilioSecurity/Sources/Keychain/KeyManager.swift
  TwilioVerify/TwilioSecurity/Sources/Storage/SecureStorage.swift
  TwilioVerify/TwilioSecurity/Sources/Storage/SecurityStorage.swift
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift
  TwilioVerifyDemo/TwilioVerifyDemo/Common/AppDelegate.swift
  TwilioVerifyTests/Plans/IntegrationSuite.xctestplan
  TwilioVerifyTests/TwilioSecurity/Sources/Keychain/KeyManagerTests.swift
  TwilioVerifyTests/TwilioSecurity/Sources/Keychain/KeychainTests.swift
  TwilioVerifyTests/TwilioSecurity/Sources/Storage/SecureStorageTests.swift
  TwilioVerifyTests/TwilioSecurity/Sources/Storage/SecurityStorageTests.swift
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Enhancement

#119 Version 0.3.1
  Scripts/bump-version.swift
  TwilioVerify/Config/Version.xcconfig
Labels: Bug

#120 ACCSEC-19957 Add SDK as package dependency in sample app
  TwilioVerifyDemo/TwilioVerifyDemo.xcodeproj/project.pbxproj
Labels: Housekeeping

#121 ACCSEC-19995 Move xcconfig variables
  Scripts/bump-version.swift
  Scripts/env.sh
  Scripts/generate-docs.sh
  TwilioVerify.xcodeproj/project.pbxproj
  TwilioVerify/Config/Version.xcconfig
  TwilioVerify/Info.plist
  TwilioVerify/TwilioVerify/Sources/Domain/Factor/PushFactory.swift
  TwilioVerify/TwilioVerify/Sources/Networking/RequestHelper.swift
  TwilioVerify/TwilioVerify/Sources/TwilioVerifyConfig.swift
  fastlane/Fastfile
Labels: Enhancement
